import type { Metadata } from "next";
import "../../globals.css";
export const metadata: Metadata = {
	title: "Sign in to Gemini",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return <html lang="en">{children}</html>;
}
