import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import QueryMenu from "@/components/QueryMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function ProductsLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex flex-col">
					<div className="flex flex-row gap-[20px] m-[2px] p-[10px] outline outline-2 outline-green-600">
						<QueryMenu />
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
